### ISSUE TITLE
Why is the project depending on a version of RestSharp.dll without a publicKeyToken?

### ISSUE THREAD

**Issue by bounav** [DocRaptor/docraptor-csharp#28]
When docraptor is the only dependency in a project that uses RestSharp every works fine.

However if you happen have another dependency that also depends on RestSharp or if you wan to depend on a different version of Resharp a file load exception is thrown:

```
Inner Exception: FileLoadException

Inner Exception Message: Could not load file or assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)


StackTrace:

   at DocRaptor.Client.Configuration.set_BasePath(String value)
   at DocRaptor.Client.Configuration..ctor()
   at DocRaptor.Client.Configuration..cctor()
```

From looking at DocRaptor.dll in dot peek I can see that the .DLL has a reference to `RestSharp, Version=105.2.3, Culture=neutral, PublicKeyToken=null`.

The problem is the `PublicKeyToken=null` part.

It should be `PublicKeyToken=598062e77f915f75`.

**Comment by jason-o-matic** [comment]
Is there any chance you could provide a small example command line project that exhibits the issue? This would be a huge help debugging.

**Comment by bounav** [comment]
> Is there any chance you could provide a small example command line project that exhibits the issue? This would be a huge help debugging.

Hi Jason, [here is a repro CLI project](https://github.com/comsechq/docraptor-example) as requested. You just need to clone it and hit F5 to trigger the issue.

**Comment by bounav** [comment]
Hey, is this project still actively maintained? Should it be archived if not?

**Comment by jason-o-matic** [comment]
Sorry for the delay, and thanks for the example!

When I [view that lib]( https://nuget.info/packages/RestSharp/105.2.3 ), under `lib/net45/RestSharp.dll` I see `PublicKeyToken=null` which matches what you're seeing.

I'm not super familiar with csharp, but is there a way for us to add the `PublicKeyToken` to the DLL after we've downloaded it, since the one we're downloading doesn't have it already?

I think another approach would be for us to switch from the openapi-generator for [csharp]( https://github.com/OpenAPITools/openapi-generator/blob/v6.6.0/docs/generators/csharp.md ) to [csharp-netcore]( https://github.com/OpenAPITools/openapi-generator/blob/v6.6.0/docs/generators/csharp-netcore.md ). It seems csharp-netcore removes v4.5 from the `targetFramework` options, which gives me pause. Again, not being super familiar with csharp, how problematic might it be to drop support for v4.5?

**Comment by bounav** [comment]
No worries.

To fix the issue I raised, it _should_ only be be a matter of updating the dependency to a more recent version of `restsharp` (and you'll automatically get a version of that DLL that has it's publicKeyToken set). 
Then compile, then build and release and updated `docarptor-csharp` nuget package.

Re your suggestion to use openapi, yes, it would be much better in my opinion.

Is there a URL where a _oas3.json_ document exists for doc raptor api?

If such a file exists, it should just be a matter of adding a [service reference to the file as documented here](https://learn.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-7.0).

**Comment by bounav** [comment]
Intesresting, I just spotted this paragraph in the repo's README.md

> Don't let swagger downgrade RestSharp to 105.1.0; it will try.

Sounds like this issue was know by someone in the team... can you _please_ update your **Restsharp** dependency!? Then is issue could be closed.

**Comment by aespitia** [comment]
running into same issue, trying to update to .net 10 with a more recent RestSharp and it's breaking docraptor
